# Site settings
title: Pritish's blog
description: I am setting up this blog to collect my thoughts

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hitchhiker.ma" # the base hostname & protocol for your site

permalink: none

author:
  fullname: Pritish Patil
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: iampritishpatil
  twitter: iampritishpatil
  disqus: iampritishpatil

google_analytics: 'UA-71923221-1'

# Build settings
markdown: kramdown