# Site settings
title: Pritish's blog
description: I am setting up this blog to collect my thoughts

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Pritish
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: iampritishpatil
  twitter: iampritishpatil
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown